//! Files no package's manifest vouches for whose exact content is what a
//! named generator makes from packaged files. On every Debian-family host
//! they would otherwise read as Unpackaged: /etc/nsswitch.conf, which
//! libc-bin copies from its template, and the /etc/pam.d/common-* stacks
//! pam-auth-update assembles from per-package profiles. On Fedora, rpm owns
//! the PAM stacks authselect renders, but as %ghost files with no digest, so
//! they would read as integrity unknown.
//!
//! The file is regenerated here the way its generator does it, from the
//! generator's inputs, and compared byte for byte. It is Reproduced only when
//! every input is itself packaged and intact. Any other byte, an added
//! `auth sufficient pam_permit.so` included, leaves it Unpackaged.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::entry::{Integrity, Provenance};
use crate::root::Root;

use super::Answers;

const CAP: usize = 256 * 1024;

const NSSWITCH: &str = "etc/nsswitch.conf";
const NSSWITCH_TEMPLATE: &str = "usr/share/libc-bin/nsswitch.conf";

const PAM_TYPES: [&str; 5] = ["auth", "account", "password", "session", "session-noninteractive"];
const PAM_TEMPLATES: &str = "usr/share/pam";
const PAM_PROFILES: &str = "usr/share/pam-configs";
const PAM_SAVED: &str = "var/lib/pam";

const AUTHSELECT_CONF: &str = "etc/authselect/authselect.conf";
const AUTHSELECT_PAM: [&str; 6] =
    ["system-auth", "password-auth", "fingerprint-auth", "smartcard-auth", "switchable-auth", "postlogin"];
const AUTHSELECT_PREAMBLE: &str = "# Generated by authselect\n\
# Do not modify this file manually, use authselect instead. Any user changes will be overwritten.\n\
# You can stop authselect from managing your configuration by calling 'authselect opt-out'.\n\
# See authselect(8) for more details.\n\n";

fn read(root: &Root, rel: &Path) -> Option<Vec<u8>> {
    root.read_capped(rel, CAP).ok().filter(|(_, truncated)| !truncated).map(|(b, _)| b)
}

/// For each wanted path this module can reproduce, the packaged files the
/// reproduction reads, whose verdicts must be looked up alongside it.
pub fn inputs(root: &Root, wanted: &std::collections::BTreeSet<PathBuf>) -> Vec<PathBuf> {
    let mut out = Vec::new();
    for path in wanted {
        if path == Path::new(NSSWITCH) {
            out.push(PathBuf::from(NSSWITCH_TEMPLATE));
        } else if let Some(ty) = pam_type(path) {
            out.push(Path::new(PAM_TEMPLATES).join(format!("common-{ty}")));
            out.extend(saved_modules(root, ty).into_iter().map(|m| Path::new(PAM_PROFILES).join(m)));
        } else if let Some(name) = authselect_name(path) {
            if let Some((dir, _)) = authselect_config(root) {
                out.push(dir.join(name));
            }
        }
    }
    out
}

/// Verdicts for the wanted paths no package claimed and this module can
/// reproduce from packaged, intact inputs.
pub fn classify(root: &Root, wanted: &std::collections::BTreeSet<PathBuf>, answers: &Answers) -> Answers {
    let intact = |p: &Path| {
        matches!(answers.get(p), Some(Provenance::Packaged { integrity: Integrity::Intact, .. }))
    };
    let mut out = Answers::new();
    for path in wanted {
        // A verdict a package database gave stands, unless it is a file the
        // database owns without a digest (rpm's %ghost), which says nothing
        // about its content.
        match answers.get(path) {
            None | Some(Provenance::Packaged { integrity: Integrity::Unknown, .. }) => {}
            Some(_) => continue,
        }
        let (expected, inputs, by) = if path == Path::new(NSSWITCH) {
            let Some(Provenance::Packaged { package, .. }) = answers.get(Path::new(NSSWITCH_TEMPLATE)) else { continue };
            let by = format!("{package}, identical to /{NSSWITCH_TEMPLATE}");
            (read(root, Path::new(NSSWITCH_TEMPLATE)), vec![PathBuf::from(NSSWITCH_TEMPLATE)], by)
        } else if let Some(ty) = pam_type(path) {
            let template = Path::new(PAM_TEMPLATES).join(format!("common-{ty}"));
            let modules = saved_modules(root, ty);
            let mut inputs: Vec<PathBuf> = modules.iter().map(|m| Path::new(PAM_PROFILES).join(m)).collect();
            inputs.push(template.clone());
            (pam_auth_update(root, ty, &template, &modules), inputs, "pam-auth-update".to_string())
        } else if let Some(name) = authselect_name(path) {
            let Some((dir, features)) = authselect_config(root) else { continue };
            let template = dir.join(name);
            // A profile without this file renders it empty, preamble only.
            let (rendered, inputs) = match read(root, &template) {
                Some(t) => (authselect_render(&t, &features), vec![template]),
                None if !root.exists(&template) => (Some(Vec::new()), Vec::new()),
                None => continue,
            };
            let expected = rendered.map(|r| [AUTHSELECT_PREAMBLE.as_bytes(), &r].concat());
            (expected, inputs, "authselect".to_string())
        } else {
            continue;
        };
        if !inputs.iter().all(|p| intact(p)) {
            continue;
        }
        if let (Some(expected), Some(actual)) = (expected, read(root, path)) {
            if expected == actual {
                out.insert(path.clone(), Provenance::Reproduced { by });
            }
        }
    }
    out
}

fn pam_type(path: &Path) -> Option<&'static str> {
    let name = path.strip_prefix("etc/pam.d").ok()?.to_str()?.strip_prefix("common-")?;
    PAM_TYPES.iter().copied().find(|t| *t == name)
}

/// The profiles pam-auth-update last used for one stack, in its order, from
/// the state it saves beside it. `null` is its placeholder for an empty
/// Primary block, not a profile.
fn saved_modules(root: &Root, ty: &str) -> Vec<String> {
    let Some(bytes) = read(root, &Path::new(PAM_SAVED).join(ty)) else { return Vec::new() };
    String::from_utf8_lossy(&bytes)
        .lines()
        .filter_map(|l| l.strip_prefix("Module: "))
        .map(str::trim)
        .filter(|m| *m != "null" && !m.is_empty() && !m.contains('/') && *m != "." && *m != "..")
        .map(String::from)
        .collect()
}

/// A pam-configs profile, parsed as pam-auth-update's parse_pam_profile does.
fn profile(root: &Root, name: &str) -> Option<BTreeMap<String, String>> {
    let bytes = read(root, &Path::new(PAM_PROFILES).join(name))?;
    let text = String::from_utf8_lossy(&bytes);
    let mut p: BTreeMap<String, String> = BTreeMap::new();
    let mut field = String::new();
    for line in text.split_inclusive('\n') {
        // ^(\S+):\s+(.*)\s*$ — the whitespace after the colon may be the
        // newline itself, which leaves the value empty.
        let head = line.split(|c: char| c.is_whitespace()).next().unwrap_or_default();
        let after = &line[head.len()..];
        if let (Some(name), true) = (head.strip_suffix(':'), after.starts_with(char::is_whitespace) && !head.is_empty()) {
            field = name.strip_suffix("-Final").unwrap_or(name).to_string();
            let value = after.trim_start_matches(char::is_whitespace);
            let value = value.strip_suffix('\n').unwrap_or(value);
            if field != "Conflicts" {
                p.insert(field.clone(), value.to_string());
            }
        } else {
            let t = line.trim();
            let v = p.entry(field.clone()).or_default();
            if !t.is_empty() {
                v.push('\n');
                v.push_str(t);
            }
            let stripped = v.trim_start_matches(|c: char| c == '\n' || c.is_whitespace()).to_string();
            *v = stripped;
            // pam-auth-update drops a profile naming a module it no longer
            // supports.
            if v.contains("pam_tally") {
                return None;
            }
        }
    }
    if p.get("Session-Interactive-Only").map(String::as_str) != Some("yes") {
        for suffix in ["-Type", "", "-Initial"] {
            if let Some(v) = p.get(&format!("Session{suffix}")).cloned() {
                p.insert(format!("Session-noninteractive{suffix}"), v);
            }
        }
    }
    Some(p)
}

/// /etc/pam.d/common-`ty` as pam-auth-update's create_from_template writes it
/// from the packaged template, with no local edits merged in.
fn pam_auth_update(root: &Root, ty: &str, template: &Path, modules: &[String]) -> Option<Vec<u8>> {
    let template = read(root, template)?;
    let template = String::from_utf8(template).ok()?;
    let mut profiles = Vec::new();
    for m in modules {
        profiles.push((m.clone(), profile(root, m)?));
    }
    let uctype = {
        let mut c = ty.chars();
        c.next().map(|f| f.to_ascii_uppercase().to_string() + c.as_str()).unwrap_or_default()
    };
    let printed = ty.strip_suffix("-noninteractive").unwrap_or(ty);

    let block = |val: &str, out: &mut String| -> Option<()> {
        let chosen: Vec<&BTreeMap<String, String>> = profiles
            .iter()
            .map(|(_, p)| p)
            .filter(|p| p.get(&format!("{uctype}-Type")).is_some_and(|t| !t.is_empty() && t == val))
            .collect();
        let lines_for = |p: &BTreeMap<String, String>, pos: usize| -> String {
            let initial = p.get(&format!("{uctype}-Initial")).filter(|v| !v.is_empty() && *v != "0");
            match (pos, initial) {
                (0, Some(v)) => v.clone(),
                _ => p.get(&uctype).cloned().unwrap_or_default(),
            }
        };
        let mut count: i64 =
            chosen.iter().enumerate().map(|(i, p)| lines_for(p, i).split('\n').filter(|l| !l.is_empty()).count() as i64).sum();
        if val == "Additional" {
            count -= 1;
        }
        if val == "Primary" && count == 0 {
            out.push_str(&format!("{printed}\t[default=1]\t\t\tpam_permit.so\n"));
        }
        for (i, p) in chosen.iter().enumerate() {
            let output = lines_for(p, i);
            let lines: Vec<&str> = output.split('\n').collect();
            // perl's split drops trailing empty fields.
            let keep = lines.iter().rposition(|l| !l.is_empty()).map_or(0, |n| n + 1);
            for line in &lines[..keep] {
                out.push_str(printed);
                out.push('\t');
                out.push_str(&merge_one_line(line, count)?);
                count -= 1;
            }
        }
        Some(())
    };

    let mut out = String::new();
    let mut state = 0;
    for line in template.split_inclusive('\n') {
        if state == 1 {
            if line.starts_with("# here's the fallback if no module succeeds") {
                out.push_str(line);
                state = 2;
            }
            continue;
        }
        if state == 3 {
            if line.starts_with("# end of pam-auth-update config") {
                out.push_str(line);
                state = 4;
            }
            continue;
        }
        out.push_str(line);
        if state == 0 && line.starts_with("# here are the per-package modules (the \"Primary\" block)") {
            block("Primary", &mut out)?;
            state = 1;
        } else if state == 2 && line.starts_with("# and here are more per-package modules (the \"Additional\" block)") {
            block("Additional", &mut out)?;
            state = 3;
        }
    }
    (state == 4).then(|| out.into_bytes())
}

/// pam-auth-update's merge_one_line with no local edits: the control and
/// module as the profile spells them, every `end` in them replaced by the
/// jump count, then one space and the options joined by single spaces — so
/// a line with no options ends in a space.
fn merge_one_line(line: &str, count: i64) -> Option<String> {
    // ^((\[[^]]+\]|\w+)\s+\S+)\s*(.*)
    let control_end = if line.starts_with('[') {
        line.find(']')? + 1
    } else {
        let n = line.find(|c: char| !(c.is_alphanumeric() || c == '_')).unwrap_or(line.len());
        if n == 0 {
            return None;
        }
        n
    };
    let rest = &line[control_end..];
    let ws = rest.len() - rest.trim_start().len();
    if ws == 0 {
        return None;
    }
    let after_ws = &rest[ws..];
    let module_len = after_ws.find(char::is_whitespace).unwrap_or(after_ws.len());
    if module_len == 0 {
        return None;
    }
    let modline = &line[..control_end + ws + module_len];
    let opts: Vec<&str> = after_ws[module_len..].split_whitespace().collect();
    Some(format!("{} {}\n", modline.replace("end", &count.to_string()), opts.join(" ")))
}

fn authselect_name(path: &Path) -> Option<&'static str> {
    let name = path.strip_prefix("etc/pam.d").ok()?.to_str()?;
    AUTHSELECT_PAM.iter().copied().find(|n| *n == name)
}

/// The profile directory and features authselect.conf names: its first
/// non-empty line is the profile id, the rest are features. A vendor profile
/// of that id is used before a default one, as authselect does; a custom one
/// lives in /etc and is nobody's package.
fn authselect_config(root: &Root) -> Option<(PathBuf, Vec<String>)> {
    let bytes = read(root, Path::new(AUTHSELECT_CONF))?;
    let text = String::from_utf8(bytes).ok()?;
    let mut lines = text.lines().map(str::trim).filter(|l| !l.is_empty());
    let id = lines.next()?;
    if id.contains("..") {
        return None;
    }
    let dir = match id.strip_prefix("custom/") {
        Some(custom) => Path::new("etc/authselect/custom").join(custom),
        None => ["usr/share/authselect/vendor", "usr/share/authselect/default"]
            .iter()
            .map(|d| Path::new(d).join(id))
            .find(|d| root.exists(d))?,
    };
    Some((dir, lines.map(String::from).collect()))
}

/// authselect's template_generate (util/template.c, 1.7.1): each operator is
/// found left to right and applied in place, removed bytes become NUL, then
/// the NULs are shaken out and every line is trimmed on the right the way
/// string_trim_right does it.
fn authselect_render(template: &[u8], features: &[String]) -> Option<Vec<u8>> {
    let mut buf = template.to_vec();
    if buf.contains(&0) {
        return None;
    }
    let len = buf.len();
    let mut features = features.to_vec();
    let mut at = 0;
    while let Some(op) = find_operator(&buf, at) {
        let enabled = evaluate(&op.expression, &features)?;
        match op.kind {
            OpKind::Continue if enabled => remove_line(&mut buf, op.start),
            OpKind::Continue => buf[op.start..].iter_mut().take_while(|b| **b != 0).for_each(|b| *b = 0),
            OpKind::Stop if !enabled => remove_line(&mut buf, op.start),
            OpKind::Stop => buf[op.start..].iter_mut().take_while(|b| **b != 0).for_each(|b| *b = 0),
            OpKind::Include if enabled => buf[op.start..op.end].fill(0),
            OpKind::Include => remove_line(&mut buf, op.start),
            OpKind::Exclude if !enabled => buf[op.start..op.end].fill(0),
            OpKind::Exclude => remove_line(&mut buf, op.start),
            OpKind::Imply => {
                if enabled && !features.contains(&op.value) {
                    features.push(op.value.clone());
                }
                remove_line(&mut buf, op.start);
            }
            OpKind::If => {
                let with = if enabled { op.if_true.as_bytes() } else { op.if_false.as_bytes() };
                if with.len() <= op.end - op.start {
                    buf[op.start..op.start + with.len()].copy_from_slice(with);
                    buf[op.start + with.len()..op.end].fill(0);
                }
            }
        }
        at = op.end;
        while at < len && buf[at] == 0 {
            at += 1;
        }
    }
    let shaken: Vec<u8> = buf.into_iter().filter(|b| *b != 0).collect();
    if shaken.is_empty() {
        return Some(Vec::new());
    }
    let lines: Vec<&[u8]> = shaken.split(|b| *b == b'\n').collect();
    let trimmed: Vec<&[u8]> = lines
        .iter()
        .map(|l| {
            if l.is_empty() {
                return *l;
            }
            let mut end = l.len() - 1;
            while end > 0 && l[end].is_ascii_whitespace() || end > 0 && l[end] == 0x0b {
                end -= 1;
            }
            &l[..=end]
        })
        .collect();
    Some(trimmed.join(&b'\n'))
}

/// string_remove_line: from the start of the line holding `at` through its
/// newline, or to the next NUL.
fn remove_line(buf: &mut [u8], at: usize) {
    let mut left = at;
    while left > 0 && buf[left - 1] != b'\n' {
        left -= 1;
    }
    let mut i = left;
    while i < buf.len() && (i < at || buf[i] != 0) {
        let newline = buf[i] == b'\n';
        buf[i] = 0;
        i += 1;
        if newline {
            break;
        }
    }
}

enum OpKind {
    Continue,
    Stop,
    Include,
    Exclude,
    Imply,
    If,
}

struct Op {
    kind: OpKind,
    start: usize,
    end: usize,
    expression: String,
    if_true: String,
    if_false: String,
    value: String,
}

/// The next `{...}` operator at or after `from`, as authselect's regular
/// expression finds them: within one line, braces never nested, an
/// expression free of `{}|:`, values free of `{}|`, a feature free of
/// `{}"|`. Scanning stops at the first NUL, where C's string ends.
fn find_operator(buf: &[u8], from: usize) -> Option<Op> {
    let end_of_string = buf[from..].iter().position(|b| *b == 0).map_or(buf.len(), |p| from + p);
    let text = &buf[from..end_of_string];
    let mut i = 0;
    while let Some(open) = text[i..].iter().position(|b| *b == b'{').map(|p| i + p) {
        i = open + 1;
        let Some(close) = text[open + 1..].iter().position(|b| matches!(b, b'{' | b'}' | b'\n')).map(|p| open + 1 + p) else {
            break;
        };
        if text[close] != b'}' {
            continue;
        }
        let Ok(inner) = std::str::from_utf8(&text[open + 1..close]) else { continue };
        let expr_ok = |e: &str| !e.is_empty() && !e.contains(['|', ':']);
        let mut op = Op {
            kind: OpKind::If,
            start: from + open,
            end: from + close + 1,
            expression: String::new(),
            if_true: String::new(),
            if_false: String::new(),
            value: String::new(),
        };
        let line_op = [
            ("continue if ", OpKind::Continue),
            ("stop if ", OpKind::Stop),
            ("include if ", OpKind::Include),
            ("exclude if ", OpKind::Exclude),
        ]
        .into_iter()
        .find_map(|(p, k)| inner.strip_prefix(p).map(|e| (k, e)));
        if let Some((kind, e)) = line_op {
            if expr_ok(e) {
                op.kind = kind;
                op.expression = e.to_string();
                return Some(op);
            }
        } else if let Some(rest) = inner.strip_prefix("if ") {
            let Some((e, values)) = rest.split_once(':') else { continue };
            let (t, f) = values.split_once('|').unwrap_or((values, ""));
            if expr_ok(e) && !f.contains('|') {
                op.expression = e.to_string();
                op.if_true = t.to_string();
                op.if_false = f.to_string();
                return Some(op);
            }
        } else if let Some(rest) = inner.strip_prefix("imply \"") {
            let Some((feature, e)) = rest.split_once("\" if ") else { continue };
            if !feature.is_empty() && !feature.contains(['"', '|']) && expr_ok(e) {
                op.kind = OpKind::Imply;
                op.expression = e.to_string();
                op.value = feature.to_string();
                return Some(op);
            }
        }
    }
    None
}

/// authselect's evaluator (util/evaluator.c): left to right, no precedence,
/// `not` toggling the next operand, parentheses nesting. None where
/// authselect reports an error and writes nothing.
fn evaluate(expression: &str, features: &[String]) -> Option<bool> {
    let mut cursor = expression.as_bytes();
    machine(&mut cursor, 0, features)
}

#[derive(Clone, Copy, PartialEq)]
enum State {
    Begin,
    Str,
    Not,
    Sub,
    Operator,
    End,
}

fn next_token<'a>(cursor: &mut &'a [u8]) -> Option<&'a [u8]> {
    while cursor.first().is_some_and(|c| *c == b' ' || *c == b'\t') {
        *cursor = &cursor[1..];
    }
    let token = match cursor.first() {
        None => &cursor[..0],
        Some(b'(' | b')') => &cursor[..1],
        Some(b'"') => {
            let close = cursor[1..].iter().position(|c| *c == b'"')? + 1;
            &cursor[..=close]
        }
        Some(_) => {
            let n = cursor.iter().position(|c| !c.is_ascii_alphabetic()).unwrap_or(cursor.len());
            &cursor[..n]
        }
    };
    *cursor = &cursor[token.len()..];
    Some(token)
}

fn machine(cursor: &mut &[u8], depth: usize, features: &[String]) -> Option<bool> {
    let (mut state, mut result, mut negation, mut operator) = (State::Begin, false, false, None::<bool>);
    loop {
        let token = next_token(cursor)?;
        if token.is_empty() {
            break;
        }
        let next = match token[0] {
            b'"' => State::Str,
            b'(' => State::Sub,
            b')' => State::End,
            _ => match token.to_ascii_lowercase().as_slice() {
                b"not" => State::Not,
                b"and" | b"or" => State::Operator,
                _ => return None,
            },
        };
        let feature = || features.iter().any(|f| f.as_bytes() == &token[1..token.len() - 1]);
        // operator: None, Some(true) for and, Some(false) for or.
        let combine = |result: bool, operator: Option<bool>, value: bool| match operator {
            None => value,
            Some(true) => result && value,
            Some(false) => result || value,
        };
        match state {
            State::Begin | State::Not | State::Operator => match next {
                State::Str => {
                    let v = feature() != negation;
                    result = combine(result, if state == State::Begin { None } else { operator }, v);
                    negation = false;
                }
                State::Not => negation = !negation,
                State::Sub => {
                    let v = machine(cursor, depth + 1, features)? != negation;
                    result = combine(result, if state == State::Begin { None } else { operator }, v);
                    negation = false;
                }
                State::End if state != State::Begin && depth > 0 => {}
                _ => return None,
            },
            State::Str | State::Sub => match next {
                State::Operator => operator = Some(token.eq_ignore_ascii_case(b"and")),
                State::End if depth > 0 => return Some(result),
                _ => return None,
            },
            State::End => {
                if depth == 0 {
                    return None;
                }
            }
        }
        state = next;
    }
    if depth != 0 || matches!(state, State::Operator | State::Not | State::Begin) {
        return None;
    }
    Some(result)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_line_is_merged_the_way_pam_auth_update_merges_it() {
        assert_eq!(
            merge_one_line("[success=end default=ignore]\tpam_unix.so nullok", 1).unwrap(),
            "[success=1 default=ignore]\tpam_unix.so nullok\n"
        );
        assert_eq!(merge_one_line("required\tpam_unix.so", 0).unwrap(), "required\tpam_unix.so \n", "no options: a trailing space");
        assert_eq!(merge_one_line("optional  pam_x.so  a   b", 3).unwrap(), "optional  pam_x.so a b\n");
        assert!(merge_one_line("\tpam_unix.so", 0).is_none());
    }

    #[test]
    fn authselect_expressions_evaluate_left_to_right() {
        let f = |names: &[&str]| names.iter().map(|s| s.to_string()).collect::<Vec<_>>();
        let on = f(&["a", "b"]);
        assert_eq!(evaluate("\"a\"", &on), Some(true));
        assert_eq!(evaluate("\"c\"", &on), Some(false));
        assert_eq!(evaluate("not \"c\"", &on), Some(true));
        assert_eq!(evaluate("\"a\" and not \"b\"", &on), Some(false));
        // No precedence: (c or a) and b, left to right.
        assert_eq!(evaluate("\"c\" or \"a\" and \"b\"", &on), Some(true));
        assert_eq!(evaluate("\"a\" and (\"c\" or \"b\")", &on), Some(true));
        assert_eq!(evaluate("NOT \"a\"", &on), Some(false), "operators match without regard to case");
        assert_eq!(evaluate("\"a\" and", &on), None, "an expression may not end on an operator");
        assert_eq!(evaluate("\"a\")", &on), None);
        assert_eq!(evaluate("(\"a\"", &on), None);
        assert_eq!(evaluate("\"a", &on), None);
    }

    #[test]
    fn an_authselect_template_renders_the_way_authselect_renders_it() {
        let f = vec!["with-x".to_string(), "with-ctx".to_string()];
        let t = b"auth  required  pam_env.so\n\
                  auth  sufficient  pam_x.so     {include if \"with-x\"}\n\
                  auth  sufficient  pam_y.so     {include if \"with-y\"}\n\
                  auth  sufficient  pam_unix.so {if not \"without-nullok\":nullok}\n\
                  auth  required  pam_z.so {if \"with-y\":yes|no}   \n\
                  {imply \"with-y\" if \"with-ctx\"}\n\
                  auth  optional  pam_later.so {include if \"with-y\"}\n\
                  \x20\x20\x20\n\
                  auth  required  pam_deny.so\n";
        let out = String::from_utf8(authselect_render(t, &f).unwrap()).unwrap();
        assert_eq!(
            out,
            "auth  required  pam_env.so\n\
             auth  sufficient  pam_x.so\n\
             auth  sufficient  pam_unix.so nullok\n\
             auth  required  pam_z.so no\n\
             auth  optional  pam_later.so\n\
             \x20\n\
             auth  required  pam_deny.so\n",
            "a dropped line leaves nothing, padding is trimmed, an implied feature counts from its line on, \
             and a whitespace-only line keeps its first character"
        );
    }
}